# Generated by Django 3.2 on 2021-04-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VanueUname', models.CharField(db_column='VanueUname', max_length=100)),
                ('UserUname', models.CharField(db_column='UserUname', max_length=100)),
                ('Name', models.CharField(db_column='Name', max_length=100)),
                ('Email', models.CharField(db_column='Email', max_length=100)),
                ('Number', models.CharField(db_column='Number', max_length=100)),
                ('Date', models.DateField(db_column='Date')),
                ('Time', models.CharField(db_column='Time', max_length=100)),
                ('Packege', models.CharField(db_column='Packege', max_length=100)),
                ('Service', models.CharField(db_column='Service', max_length=100)),
                ('Status', models.CharField(db_column='Status', max_length=10)),
                ('VenueName', models.CharField(db_column='VenueName', default='Nothing', max_length=100)),
            ],
            options={
                'db_table': 'user_history',
            },
        ),
    ]
