# Generated by Django 3.2 on 2021-04-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('VanueUname', models.CharField(max_length=100)),
                ('UserUname', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Number', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=100)),
                ('Packege', models.CharField(max_length=100)),
                ('Service', models.CharField(max_length=100)),
                ('Status', models.CharField(default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vanues',
            fields=[
                ('VanueID', models.AutoField(primary_key=True, serialize=False)),
                ('VanueName', models.CharField(max_length=100)),
                ('VanueAddress', models.TextField()),
                ('Description', models.TextField()),
                ('Contact', models.CharField(max_length=10)),
                ('VanueType', models.CharField(max_length=30)),
                ('VanueBudget', models.CharField(max_length=30)),
                ('Image', models.CharField(max_length=100)),
                ('PerDayRent', models.CharField(max_length=100)),
                ('PricePerDish', models.CharField(max_length=100)),
                ('MusicRent', models.CharField(max_length=100)),
                ('CateresRent', models.CharField(max_length=100)),
                ('DecoretionPrice', models.CharField(max_length=100)),
                ('ServiceRent', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    ]
