# Generated by Django 3.2 on 2021-04-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_vanues_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vanues',
            name='Status',
        ),
        migrations.AddField(
            model_name='history',
            name='VenueName',
            field=models.CharField(default='Nothing', max_length=100),
        ),
    ]
